### ISSUE TITLE
[Suggestion] Config File

### ISSUE THREAD

**Issue by Gamemassa** [NiceKaleido/Enchantments-Encore#4]
Hi, would it be possible to add a config file to enable/disable certain enchantments, control where they can/can't spawn, and control incompatibilities?

**Comment by NiceKaleido** [comment]
Config files are not possible due to minecraft data pack limitations. For changing the incompabilities you'd have to edit the files themselves.

**Comment by Gamemassa** [comment]
> Config files are not possible due to minecraft data pack limitations. For changing the incompabilities you'd have to edit the files themselves.

Ok. So can I do that via datapack or do I have to modify the actual Enchantments Encore jar file?
